### ISSUE TITLE
Ancient Scepter listed as tier 1 white item

### ISSUE THREAD

**Issue by PhantomMs1** [ThinkInvis/RoR2-ClassicItems#101]
After the latest update the Ancient Scepter T3 Red item is showing up in the White item list making it extremely OP. 

*edit* turns out there are a few items mixed up in the different tiers.
Thanks for a great mod!

**Comment by ThinkInvis** [comment]
Fixed in ThinkInvis/RoR2-TILER2@4dd30dd2c5a57c456344bbfa758675fa82b5e262.
