### ISSUE TITLE
Bugged "Item"? Patch 1.2.3

### ISSUE THREAD

**Issue by ClarJyun** [ThinkInvis/RoR2-ClassicItems#102]
### Some blank item shows up in game and in logbook. I can't really pull up the log because it might be visual? 
![20220421104442_1](https://user-images.githubusercontent.com/104090955/164365076-43711434-d027-4848-a764-7ea3a4dce18b.jpg)
![20220421111046_1](https://user-images.githubusercontent.com/104090955/164365093-1c1690dc-b1ad-4b8c-ab6f-ae8cee729b74.jpg)

**Comment by 3Questionmarks** [comment]
I've also experienced this. If you actually pick the item up, it gives the hitlist buff, so I think its the dummy item for handling the stat increase when killing an enemy that has the debuff from hitlist.

**Comment by ThinkInvis** [comment]
Fixed by 21bd269f141faeacf4f399766bbb2e28f462151f.
