### ISSUE TITLE
Life Savings (and possibly Golden Gun) do not function

### ISSUE THREAD

**Issue by PollyEdaline** [ThinkInvis/RoR2-ClassicItems#105]
### Describe the Bug
This has been the case for a long while, so I'd like to try and get to the bottom of this. Reference #72 and #84. This is, of course, on my [Accretion modpack](https://thunderstore.io/package/Polly/Accretion/). Life Savings does not correctly generate any gold with any config settings, and Golden Gun throws an error into the log. This is on any character, vanilla or modded, although all of the characters in this pack are modded in some way. This is supposedly related to ShareSuite.

### To Reproduce
1. Get at least one stack of Life Savings.
2. Fail to generate any additional income.

### Expected Behavior
Money please

### Console Log
[LogOutput.log](https://github.com/ThinkInvis/RoR2-ClassicItems/files/8636072/LogOutput.log)

**Comment by ThinkInvis** [comment]
I'm fairly confident that neither of these are directly resolvable in the scope of Classic Items, especially the issue with Life Savings. I've implemented a workaround for the issue with Golden Gun (bb5aa07ceb1eaacfab1e34c670ed636f5a8a6a1d), but it mostly points to a bad IL patch in another mod (removing or altering code that it shouldn't be for mod compatibility reasons).

The issue with Life Savings appears to be entirely a ShareSuite bug. Life Savings works fine without ShareSuite installed, and stops working once ShareSuite is installed. It has ShareSuite integration that appears to be correct as per their public API.

The Golden Gun error is on an IL match that really shouldn't be failing, even if other mods are patching the same method. Culprit is likely to be something that changes how Crowbar works, but that's not a guarantee. Said other mod should change its own IL patch to be more compatible. I'll restructure the item's mechanics to use RecalculateStats whenever the percentage buff count changes instead; this will be slightly less performant and responsive, but avoids the problem of IL incompatibility.

**Comment by ThinkInvis** [comment]
32ead15e20bdbac60dd1f7bb8b806e870db8364d appears to allow Life Savings to work with ShareSuite installed in singleplayer. I have no idea if it's going to lead to duplicate money in multiplayer or not; either way, I shouldn't have to do this, as changing the shared money value *should* also be modifying local money value on its own.
