### ISSUE TITLE
Bizarre mod incompatibility

### ISSUE THREAD

**Issue by Skitter1200** [ThinkInvis/RoR2-ClassicItems#108]
When used alongside the Forgotten Relics mod, one of that mod's enemies experiences (the Coil Golem) experiences hilariously massive overspawns (several hundred of a boss-tier enemy, yyyyep) to the point of lagging the game to "minutes per frame" if not crashing outright.

Steps to Reproduce

1: Install ClassicItems, Forgotten Relics, and dependencies
2: Play the game normally
3: Reach Rallypoint Delta
4: Suffer

**Comment by ThinkInvis** [comment]
Closing due to project archival; may have also been resolved by the recent TILER2 update for split R2API assemblies.
