### ISSUE TITLE
Game Breaks unless everybody has the exact same configfile

### ISSUE THREAD

**Issue by Hominghead** [ThinkInvis/RoR2-ClassicItems#22]
I set HeadstompersV2 Parameter to false and Headstompers Item to disabled (false), and whenver i try to join my friends who have the default configfile with the changed HeadstompersV2 and enabled  Classic Headstompers the game just literally breaks and nothing works anymore.

**Comment by ThinkInvis** [comment]
This is a potential issue with all mods that have config files; the solution is to not join players with different settings. Either change yours to match theirs, or tell anyone you're joining to do the same. Sending the entire config file (e.g. over Discord) or using a mod manager with profiles are both options.

**Comment by Hominghead** [comment]
u wot?

No mod does this bullshit, just load settings from host. also display some proper exception because the Log throws literally nothing

**Comment by ThinkInvis** [comment]
The item disable configs work by completely preventing the item from being registered. Items can only be added before ItemCatalog setup, which happens during game launch; there's no easy nor safe way to add a disabled item after that. Trying to do so would likely cause more problems than it solves. I'll look into throwing an error and/or refusing connection on config mismatch, but automatic switching isn't an option.
