### ISSUE TITLE
Photon jetpack hooks throw if body is of a type derived from characterbody

### ISSUE THREAD

**Issue by Reinms** [ThinkInvis/RoR2-ClassicItems#25]
The Reflection.InvokeMethod line in photon jetpack hooks will throw an error if the instance of body is not of type CharacterBody.

Additionally, I would generally advise against calling reflection per-frame as it can substantially hurt performance. 

Solution: cache a delegate. This does two things, first it is faster, and second, it eliminates the method discovery issue that throws the exception when you are searching for a method in a type that inherits CharacterBody. Also has side benefit of having much cleaner usage syntax.

Note: this was written on mobile. so there may be some typos.
```cs
//Going to need using System.Linq.Expressions; using RoR2; using System.Reflection
public static class CharacterBodyExtensions
{
    //Delegate that stores the compiled function
    private static Action<CharacterBody,BuffIndex,int> _setBuffCount;

    //Extension method so you can pretend it is public
    public static void SetBuffCount( this CharacterBody body, BuffIndex buffType, int newCount )
    {
        _setBuffCount( body, buffType, newCount );
    }

    //Called the first time this type is referenced, all the expensive stuff goes in here so that subsequent calls are as fast as possible.
    static CharacterBodyExtensions()
    {
        //The methodInfo that we want to compile a delegate for
        MethodInfo targetMethodInfo = typeof(RoR2.CharacterBody).GetMethod( "SetBuffCount", BindingFlags.NonPublic | BindingFlags.Instance );

        //This code below essentially stores the existing method inside our delegate

        //Defining the arguments of the function we are compiling
        var bodyParameter = Expression.Parameter( typeof(RoR2.CharacterBody), "body" );
        var buffIndexParameter = Expression.Parameter( typeof(RoR2.BuffIndex), "buffIndex" );
        var countParameter = Expression.Parameter( typeof(System.Int32), "count" );

        //The body of the function
        var functionBody = Expression.Call( bodyParameter, targetMethodInfo, buffIndexParameter, countParameter );
        var lambda = Expression.Lambda<Action<CharacterBody,BuffIndex,int>>( functionBody, bodyParameter, buffIndexParameter, countParameter );

        //Compile the expression tree and store it to the private field
        _setBuffCount = lambda.Compile();
    }
}
```

**Comment by ThinkInvis** [comment]
Thanks! The R2API wiki doesn't explain anything like this, and I don't have much experience with reflection/expressions otherwise. Out of curiosity: I never saw PhotonJetpack code throw any errors similar to the one you described... was it actively conflicting with another mod, or is that just something that *could* happen?

**Comment by Reinms** [comment]
It was conflicting pretty violently with a beta version of sniper, that is how I noticed. I don't know of anyone else who inherits CharacterBody off the top of my head.
