### ISSUE TITLE
The config to disable item doesnt work.

### ISSUE THREAD

**Issue by CSOLYOO** [ThinkInvis/RoR2-ClassicItems#35]
![image](https://user-images.githubusercontent.com/20432375/81535898-306fc000-939d-11ea-8bb6-8f29614910d5.png)
I disable the box glove and vial. Dont work.

**Comment by ThinkInvis** [comment]
As of v4.0.0, items are intended to no longer be removed from the logbook when disabled. This was causing too many issues in multiplayer. Disabled items should still: stop dropping ingame, stop being given to enemies by Evolution/missions, be unselectable from Command drops, unsubscribe their IL patches and event hooks (reducing the probability of mod conflicts), and have a [DISABLED] tag in pickup text and description (including in the logbook).
