### ISSUE TITLE
Giant Amethyst Higher Cooldown

### ISSUE THREAD

**Issue by drp527** [ThinkInvis/RoR2-ClassicItems#36]
This might have been intentional, but I didn't see anything in the changelog about it. Giant Amethyst now has a cooldown of 45 seconds, but had been using the ror1 cooldown of 8 seconds until either 4.0.0 or 4.1.0.

**Comment by ThinkInvis** [comment]
Wow, I... really don't know what happened to the cooldown definition on that. Fixed by d33e0babd1d5d315789c43b3a8815fc618d2b908.
