### ISSUE TITLE
Rex Ancient Scepter bug

### ISSUE THREAD

**Issue by Coffe-e** [ThinkInvis/RoR2-ClassicItems#37]
Currently, Ancient Scepter does not increase the radius for Rex's R ability. 
The debuff pulse, however, works completely fine.

**Ways to replicate:**
Start run as Rex.
Give yourself an Ancient Scepter
Compare to Regular R's Radius

**Comment by ThinkInvis** [comment]
Fixed by 56f2d67b4d8b6cbd5bfe12f16611f9d8d0878d86.
