### ISSUE TITLE
Telescope sight kills target immediately, causing altar to jam 99%

### ISSUE THREAD

**Issue by muyu250145545** [ThinkInvis/RoR2-ClassicItems#39]
The telescope sight will kill the target immediately. It has a chance to cause the altar to jam by 99%. It is recommended to change it to 2% to cause 999 times of damage

**Comment by ThinkInvis** [comment]
[This appears to be a bug in vanilla RoR2.](https://steamcommunity.com/app/632360/discussions/1/1647665620929409726/) Fixing it would be outside the scope of this mod.
