### ISSUE TITLE
Add Ancient Scepter skill for Captain

### ISSUE THREAD

**Issue by ThinkInvis** [ThinkInvis/RoR2-ClassicItems#46]
Double beacon casts per stage, maybe?

**Comment by Azzezima** [comment]
Probably wouldn't be that useful unless you get it on stage 1. That would take away from the "wow!" of getting a red item imo. Maybe something like turning the utility skill into one big strike?
Just a thought

**Comment by VaelophisNyx** [comment]
Could make his M2 become a laser instead of a stun

**Comment by ThinkInvis** [comment]
Fixed in 1064978f8c733583e0ccb6ea9f485c0b924c8206.
