### ISSUE TITLE
Boxing Gloves knockback scaling

### ISSUE THREAD

**Issue by MightyW0lf** [ThinkInvis/RoR2-ClassicItems#49]
Scale Boxing Gloves' knockback with the **% of target enemy health removed with the hit** instead of the damage itself. Past the first loop, the current knockback on anything that deals more damage gets ridiculous and instakills anything by smashing it into a wall (and changing the value in configuration just delays this effect at the cost of the item being useless early on).

**Comment by ThinkInvis** [comment]
Fixed by 66fa7c7e846e74d2f74c0d182ab7af48cb7ebbc2, 4d88ba1cda07a1e7c29f1cd3c171b06bec2fc5aa.
