### ISSUE TITLE
Scepter gives incorrect (inverted) upgrades for Huntress.

### ISSUE THREAD

**Issue by NanoAi** [ThinkInvis/RoR2-ClassicItems#50]
When using the Scepter on Huntress if you took Arrow Rain you'll get Rabauld, and if you took Ballista you'll get Burning Rain.
I assume this was fixed in 39f9332e1a465f37859a1f47929bb29ec371ccad however I'm creating an issue anyway.

**Comment by ThinkInvis** [comment]
Yes, that's fixed already. I've been waiting for an opportunity to update TILER2 first, but it seems like that's going to take longer than expected. I'll push an update with that commit soon.
