### ISSUE TITLE
Compatibility with ItemStatsMod 

### ISSUE THREAD

**Issue by nickg11** [ThinkInvis/RoR2-ClassicItems#52]
https://github.com/ontrigger/ItemStatsMod

Currently ItemStats mod is able to correctly add the description of your items but it does not have the scaling portion implemented. For example, if you had 3 bitter root the mod would tell you on the tooltip that you are getting 24% max health. Would it be possible to add your items to the ItemStats mod via their API.

**Comment by ThinkInvis** [comment]
I'll look into it.

**Comment by ThinkInvis** [comment]
It seems like that API (as described in their GH readme) isn't released yet, as it doesn't exist in the Thunderstore version. Waiting until an ItemStats update which releases the API to attempt implementation.

**Comment by nickg11** [comment]
conext I asked when the API will come to thunderstore

That's because 2.0 isnt released, but there is a prerelease build. Hovewer, I'd advise not to use the API for now as im planning to redo the stat calculation entirely

^
copied from issue I opened on the itemstats mod repo. So I guess it is something you can forgot about for a while

**Comment by ThinkInvis** [comment]
Fixed by 2e0f1fb75ad097e1120ca45c2dba80685167c09f.
