### ISSUE TITLE
[Bug] Disabled items are dropped by Sacrifice

### ISSUE THREAD

**Issue by fwenny** [ThinkInvis/RoR2-ClassicItems#55]

**Comment by ThinkInvis** [comment]
Almost certainly related to #42, but it's impossible to confirm that for sure until the other issue is resolved. Keeping this open until then.

**Comment by ThinkInvis** [comment]
#42 is fixed, and I haven't been able to get Sacrifice to drop anything from ClassicItems with all the Enabled configs set to false.
