### ISSUE TITLE
Make ModCompat classes Public

### ISSUE THREAD

**Issue by cheeeeeeeeeen** [ThinkInvis/RoR2-ClassicItems#61]
### Is your feature request related to a problem? Please describe.
ModCompat is `internal` and thus when I have a full dependency on it, I cannot call `ModCompat_ItemStats.enabled` due to it being internal.

### Describe the solution you'd like
Make them public, or something similar that will allow access for other mods.

### Describe alternatives you've considered
My alternative is to just copy your ModCompat files into my fork in order for them to work.

**Comment by ThinkInvis** [comment]
This is intentional, as ClassicItems is not meant for use as a direct dependency. I'll see about migrating these classes to TILER2 instead.

**Comment by ThinkInvis** [comment]
Fixed in 7bb5a58d6c8b33cc2d034c5b19ccf875597a56c7 + ThinkInvis/RoR2-TILER2@1699318b2785c03f61249a3b1abf81a44c1038fa.
