### ISSUE TITLE
Ancient Scepter + Mostly Tame Mimic (Tinker's Satchel)

### ISSUE THREAD

**Issue by Coffe-e** [ThinkInvis/RoR2-ClassicItems#65]
### Describe the Bug
Whenever a MTM mimics an ancient scepter, it causes the original to re-roll itself.

### To Reproduce
1. Start a Run.
2. Give yourself a MTM and Ancient Scepter.

### Expected Behavior
For MTM to avoid mimicking Ancient Scepter.

**Comment by ThinkInvis** [comment]
Fixed by ThinkInvis/RoR2-TILER2@ed9eccbd84415544c56339be91583462d4504350, 962dc2aae26628b37937f725456a6929cd0b8673, ThinkInvis/RoR2-TinkersSatchel@e1f60dcf4c6cc089f165ae2bb1c137c11778a749.
