### ISSUE TITLE
Equipement not trigering with kingmodUtilities

### ISSUE THREAD

**Issue by benjdidj** [ThinkInvis/RoR2-ClassicItems#66]
### Describe the Bug
When used with KingModUtilities, Equipement from RoR2-ClassicItems cannot be activated.
KingModUtilities is a dependancy for the goku and the Vegeta Mod :
https://thunderstore.io/package/kinggrinyov/

### To Reproduce
1. Dowload  and install goku or Vegeta mod with the dependancy on r2modman, or directly KingmodUtilities from :
https://thunderstore.io/package/kinggrinyov/KingModUtilities/ 
2. download  and install StartingItemsGUI (a mod that let choose starting item),
because it is going to help save time.(not necessary if you 'd like "to grind" to get an equipement from RoR2-ClassicItems)
3. run the modded game with these 3 mods.

4.In the game menu a new menu 'starting items',Click,
5  a grid with all the items and tabs on the top: click the tab 'free' and choose one equipement from the ror2classicitemmod. exit. (if there is none, maybe got to be unlocked by playing....my bad then...)
6 Start a new game and test the equipement. 
It is not working on my side.

### Console Log
later maybe.

**Comment by cheeeeeeeeeen** [comment]
It's a known issue and the mod at error is **not** ClassicItems.

Kingmodutils must be the one that must be modified.

**Comment by benjdidj** [comment]
thanks, I thought that could be the case.
Thx for the Mod

**Comment by benjdidj** [comment]
thx for youre mod :)

**Comment by ThinkInvis** [comment]
The error in question is that KingModUtilities intercepts the equipment activation event for *all* non-vanilla equipments, and fails to allow unhandled equipments from other mods to execute code. Due to the way Monomod works, mods later in the load order circumvent this and execute anyways -- meaning this bug may be intermittent as load order changes.

**Comment by benjdidj** [comment]
1 Can we affect load order ? 'i am a newb.
2 Could kingmodUtilities's autor fix something about that? in theory. Allowing unhandled equipement from other mods to execute code ?

**Comment by ThinkInvis** [comment]
No, load order is only managed by BepInEx at the moment. Dependencies would make manual load order changes difficult. As for a fix -- it should be trivial to do, but the KMU author is currently taking a break from modding.

**Comment by benjdidj** [comment]
Fair enough. Thanks for your time :)

**Comment by ThinkInvis** [comment]
Appears to have been fixed a while ago, judging by the KMU changelog. Reopen if this is not the case.
