### ISSUE TITLE
Photon Jetpack & Extra Jumps

### ISSUE THREAD

**Issue by Mlezivan** [ThinkInvis/RoR2-ClassicItems#68]
### Is your feature request related to a problem? Please describe.
Having to use extra jumps when you can fly is annoying.

### Describe the solution you'd like
When you have the Photon Jetpack, additional jumps are converted into extra fuel, as a config option.

### Describe alternatives you've considered
N/A.

### Additional context
N/A.

### Other
Great mod btw, thanks for making it!

**Comment by ThinkInvis** [comment]
Implemented via recent branch merge (final commit https://github.com/ThinkInvis/RoR2-ClassicItems/commit/6840d60338a9244b113fbb95401d52ee388f506a). Available modes are use jumps first, use jetpack first, use both simultaneously (boosted jumps), convert jumps to fuel.
