### ISSUE TITLE
Shrine of the Mountain as Item

### ISSUE THREAD

**Issue by Schattenfeuer** [ThinkInvis/RoR2-ClassicItems#69]
Hi,

I love all your mods for Risk of Rain 2.

I had the idea to get the Shrine of the Mountain as a green item or an artifact. 
Just an idea for you :D If you got time and joy.

**Comment by ThinkInvis** [comment]
That's well outside of this mod's scope -- RoR1 didn't have any equivalent to Shrine of the Mountain. This would be more suitable for Tinker's Satchel, but I'm not currently accepting content requests for that mod.

Try asking in the Risk of Rain 2 Modding Discord (accessible from Thunderstore) #ideas channel instead, or using the other resources in that server to learn to make your own mods.
