### ISSUE TITLE
Imprint Component should only fire in the server

### ISSUE THREAD

**Issue by cheeeeeeeeeen** [ThinkInvis/RoR2-ClassicItems#71]
https://github.com/ThinkInvis/RoR2-ClassicItems/blob/30556080c6520a30e017e5f0a5711ca38f6aed67/Items/T2/Imprint.cs#L112

This component should only fire in the server. Connected Clients receive NullReferenceExceptions in ImprintComponent.FixedUpdate, but to begin with, this should only be fired in the server if all it does is give a buff.

Also, it spams the RemoveBuff called on client message which causes the game to lag hard.

**Comment by ThinkInvis** [comment]
Should be fixed by 03af78b23ce68a85a241b0d0147008df1cfb1579. Testing pending #77.

**Comment by ThinkInvis** [comment]
Not seeing any NREs during dedicated server testing.
