### ISSUE TITLE
Life Savings not functioning on Nemforcer (Bug)

### ISSUE THREAD

**Issue by Coffe-e** [ThinkInvis/RoR2-ClassicItems#72]
### Describe the Bug
When you pick up a stack of Lifesavings as Nemforcer from the Enforcer mod, he doesn't gain any money.

### To Reproduce
1. Start a run as Nemforcer
2. Give yourself lifesavings

### Expected Behavior
Giving money at it's disclosed rate

### Console Log
[LogOutput.log](https://github.com/ThinkInvis/RoR2-ClassicItems/files/5665288/LogOutput.log)

**Comment by cheeeeeeeeeen** [comment]
@Coffe-e  Would this really be related to Life Savings? It works on other survivors, so why not Nemforcer? I think Nemforcer has the bug...

**Comment by Ulivax** [comment]
@cheeeeeeeeeen This bug can also be applied to the Paladin playable character (rob-PaladinMod-1.0.9) as well. As you say, probably to do with handling modded characters? Not sure about Bandit etc.

_Edit: FALSE Tried with Bandit, also no money gain from Life Savings_

Edit 2: Tried using artifact of command on Life Savings with various modded characters, here's my list:
Life Savings work on: Bandit, Gunslinger, Enforcer, Miner and all Vanilla characters.
Life Savings doesn't work on: Paladin

**Comment by ThinkInvis** [comment]
I'll try to pin this down after work on #77 is done, but it sounds like this is probably an issue with how those modded characters are set up (e.g. they may fail to have the same object structure as vanilla characters).

**Comment by ThinkInvis** [comment]
AFAIK this wound up being a ShareSuite bug (modded characters had to provide compat code and wouldn't work out-of-the-box if installed alongside ShareSuite).
