### ISSUE TITLE
Ancient Sceptre giving Engi turrets random red items

### ISSUE THREAD

**Issue by Benjamin2202** [ThinkInvis/RoR2-ClassicItems#74]
When using the Ancient Sceptre on Engi the sceptre gives random red items to the turrets
What is causing it I'm unsure 
Just thought I'd tell you of this bug :)

**Comment by ThinkInvis** [comment]
Possibly fixed by 2ab09f65e92a57af492fef85a3fc03789dbceec9. Testing pending #77.

**Comment by ThinkInvis** [comment]
Looks to be fixed.
