### ISSUE TITLE
ItemBlacklister doesn't seem to be able to actually blacklist the items in this or ChensClassicItems

### ISSUE THREAD

**Issue by Catman-232** [ThinkInvis/RoR2-ClassicItems#75]
https://thunderstore.io/package/RyanPallesen/ItemBlacklister/
It's two years old but it does still work, I made sure of it. Testing with only that mod enabled it only spawned the single item I left not blacklisted. With both classic items mods enabled it shows them all in the item list too but with every white and green item blacklisted (including the classic items) except for the Soldier's Syringe, it was constantly giving classic items and spawning them in printers and multishops, took until stage 3 for a syringe to finally drop.

I haven't the smarts to know if this is a problem with Item Blacklister rather than these item mods, but I figured I'd post this here anyway.

**Comment by cheeeeeeeeeen** [comment]
It might have something to do with mod load order. Do other modded items work?

**Comment by Catman-232** [comment]
I didn't know mod order was even a thing, always looked like bepinex was loading them in a random order. I moved blacklister after the class items mods in r2modman and it still didn't prevent them from showing up in-game. I don't use any other item mods so I don't know if this would happen for other mods, I'd guess it does though.

**Comment by cheeeeeeeeeen** [comment]
Yeah. Sadly, this might have something to do with mod loading order. The same issue happens with DebugToolKit on some of item mods.

**Comment by Catman-232** [comment]
Is it not possible to force a mod to load after others? Or maybe would it be possible to have blacklister load as if it was part of one of the classic items mods?

**Comment by cheeeeeeeeeen** [comment]
@Catman-232 It would only be possible if the blacklister got the classic items mods as soft dependency. It would be on the side of the blacklister mod.

**Comment by Catman-232** [comment]
So presumably I could edit the files of blacklister to add the dependencies to it?

Edit: I've tried this, adding both classic items mods to the dependencies on blacklister's manifest.json and also into the profile's mods.yml so r2modman lists all the dependencies they have combined. Hasn't solved the issue unfortunately. Weird that blacklister is able to list the items in the lobby but not lock them out of runs.

**Comment by cheeeeeeeeeen** [comment]
I can conclude that it's in blacklister's side. It needs to support modded items of actually locking the items.

As for dependency, it needs to be done in code and not in the json file. It needs to be compiled with the dependency specified in code.

**Comment by Catman-232** [comment]
Thanks for looking into this, hopefully RyanPallesen will be open to updating the mod for this purpose, which I imagine they should be considering all the FloodWarning stuff they've been putting out recently.
