### ISSUE TITLE
Lunar Items spawning as Green Items + Command menu bugging

### ISSUE THREAD

**Issue by Zane-Truesdale** [ThinkInvis/RoR2-ClassicItems#80]
Basically got glad when I saw this come back for the AU, but it's causing two peculiar bugs.

First one was that whenever an essence drops, the command menu would be sometimes missing items (or sometimes not display items at all). I think it does rearrange the items sometimes, but I'm not sure on that one.

The second one is odd. Whenever a Lunar coin or a Lunar item would drop, it would become a green item instead. 
I have a video of the second bug (the first one only happened like once per stage) and the LogOutput if that helps. 
[the stuff on this bug.zip](https://github.com/ThinkInvis/RoR2-ClassicItems/files/6261697/the.stuff.on.this.bug.zip)

**Comment by ThinkInvis** [comment]
Confirmed as an issue with R2API.ItemAPI. BetterUI just makes the bug weirder; without it, those Command droplets are empty instead.

**Comment by Zane-Truesdale** [comment]
Just did a run without BetterUI, seems the results were the same. Did it as a vanilla character just to be sure if it only happened with modded ones. Wanna say the buggy command droplets could be due to how the items are placed in the menu, but that would be judging on ignorance.

The lunars dropping as greens stumps me though. It also affects any items that drop in the newt shop, even from the red cauldron.

https://user-images.githubusercontent.com/45983028/113797169-bc5da980-971e-11eb-962b-3fce335e804d.mp4

**Comment by htssath** [comment]
I've had this same issue, but was using Bigger Bazzar so I thought it might be a compatibility issue. One thing I've noticed is that the last item to drop in the stage before entering bazzar (usually green) is what makes only that color drop in the bazaar. I got lucky with a boss drop and all my items were subsequently yellow when I bought lunar or exchanged items.

**Comment by ThinkInvis** [comment]
Appears to have been fixed by R2API 3.0.11.
