### ISSUE TITLE
Mod Fails To Load

### ISSUE THREAD

**Issue by VaelophisNyx** [ThinkInvis/RoR2-ClassicItems#86]
### Describe the Bug
To be clear this occurs with Tinker's Satchel too, but, items from both mods fail to load entirely as of the patch earlier today.

### Console Log
[LogOutput.log](https://github.com/ThinkInvis/RoR2-ClassicItems/files/6300504/LogOutput.log)

**Comment by ThinkInvis** [comment]
Some things in base game code/R2API which my mods depend on probably got changed. I'll need to find out what those are and rebuild; I've been too busy the past two weeks to do so, but should be able to start within a few days.

**Comment by ThinkInvis** [comment]
Should be fixed now.
