### ISSUE TITLE
bitterroot scaling past 38(37.5) stacks

### ISSUE THREAD

**Issue by milkev** [ThinkInvis/RoR2-ClassicItems#90]
### Is your feature request related to a problem? Please describe.
Nope!... just a personal obsession with having high stack counts

### Describe the feature you'd like
it would be cool if bitterroot scaled past 38 (technically 37.5) stacks. perhaps it halves its effectiveness every 128%? (16 stacks)

### Describe alternatives you've considered
1: halves effectiveness at certain intervals (ex: 4% buff after 16 stacks, 2% after 32, etc etc)
2: just doesnt have a cap
3: increases hp less, but has no cap
4: is a green item, no cap

### Additional context
None!

**Comment by ThinkInvis** [comment]
The only reason for that cap being there is to match Risk of Rain 1 item behavior as closely as possible. Even so, the cap is tied to a config option (ClassicItems / BitterRoot / HealthCap), so it can effectively be removed by setting said option to a very high value.

**Comment by ThinkInvis** [comment]
Closing as I've decided the existing config options are sufficient for this item. I'll most likely remove the cap and set a lower health amount whenever I get around to implementing #3.
