### ISSUE TITLE
Ancient Scepter - Allow for the mod's Scepter skills to be overriden, and make the skill icons accessible to other mods.

### ISSUE THREAD

**Issue by Moffein** [ThinkInvis/RoR2-ClassicItems#97]
StandaloneAncientScepter (https://thunderstore.io/package/amogus_lovers/StandaloneAncientScepter/) allows for its Scepter skills to be replaced by custom Scepter skills from other mods. Attempting to add a Scepter skill to a survivor who already has a Scepter skill for that skill slot will simply overwrite the existing one.

Also, all the icon sprites are accessible to other mods (https://github.com/DestroyedClone/AncientScepter/blob/master/AncientScepter/Assets.cs), which is useful.

**Comment by ThinkInvis** [comment]
Former point fixed in acf3e8d02b077bef737d014ad52c4a07972bbbc3. 99b77a4d47ec3f762d309e8d30b0ee172536f0d0 is the most effort/LoC I'm willing to spend on the latter at present.
