### ISSUE TITLE
after update ThinkInvis / RoR2-TILER2 to 6.1.1 - classic items stop working

### ISSUE THREAD

**Issue by xand1r** [ThinkInvis/RoR2-ClassicItems#98]
all items from the mod just don't work. icons are displayed, but stats are not given

**Comment by ThinkInvis** [comment]
This is an incompatibility with BetterUI: its ItemStats module underwent major breaking changes. A temporary fix which removes BetterUI support will be pushed to TILER2 soon; extra stats for items from this mod won't display for a while.

**Comment by xand1r** [comment]
> This is an incompatibility with BetterUI: its ItemStats module underwent major breaking changes. A temporary fix which removes BetterUI support will be pushed to TILER2 soon; extra stats for items from this mod won't display for a while.

thanks, actualy i just download old version better ui and tiler2 and I'm quite happy with it so far
